language: java
jdk:
  - openjdk17

before_install:
  - chmod +x gradlew

#addons:
#  sonarcloud:
#    token:
#      secure: "" # encrypted value of your token
script:
  - ./gradlew build
  # other script steps might be done before running the actual analysis
  - sonar-scanner

after_success:
  - ./gradlew test